### ISSUE TITLE
Singularizes tennis to tenni

### ISSUE THREAD

**Issue by deepakg** [hrbrmstr/pluralize#1]
Installed off github:
devtools::install_github("hrbrmstr/pluralize")
library(pluralize)
singularize(c('tennis'))
[1] "tenni"

**Comment by hrbrmstr** [comment]
thx. that'd be good to file an issue with the underlying JS lib.

**Comment by deepakg** [comment]
Just did: https://github.com/blakeembrey/pluralize/issues/56

**Comment by deepakg** [comment]
Fixed upstream by https://github.com/blakeembrey/pluralize/pull/57

**Comment by hrbrmstr** [comment]
and in the new pkg. #ty
