### ISSUE TITLE
Does not work with dataframes/vectors?

### ISSUE THREAD

**Issue by acircleda** [hrbrmstr/pluralize#2]
This works:
```
data <- c("tests", "nations")
singularize(data)
```

However, this does not:
```
data <- data.frame(c("tests", "nations"))
singularize(data)
```

Error: 

> Error in context_eval(join(src), private$context) : 
  TypeError: word.toLowerCase is not a function

I was trying to apply this to a large dataframe after using TidyText's unnest_tokens

**Comment by llrs** [comment]
You can apply it to the column you want via `mutate`... or `singularize(data[[1]])`

**Comment by hrbrmstr** [comment]
Aye, it works just like any of the other character vector ops work.
