### ISSUE TITLE
It converse "has" to "ha", "was" to "wa".

### ISSUE THREAD

**Issue by jjcheer** [hrbrmstr/pluralize#4]
It's a good pkg to change between plurals and singular, but I found it will converse "has" to "ha" and "was" to "wa" when I use the sigularize() function. These are not the results I want. Can you fix this? Thanks for the fantastic job.

**Comment by hrbrmstr** [comment]
There are 2 possibilities to achieve your desired result.

First: define your own custom rules to handle this situation: https://github.com/hrbrmstr/pluralize/blob/master/R/rules.R

Second: file an issue with the javascript library this package wraps: https://github.com/plurals/pluralize/issues
