### ISSUE TITLE
.onAttach prevents use of pluralize in packages

### ISSUE THREAD

**Issue by gtm19** [hrbrmstr/pluralize#5]
Small issue I had when trying to import `pluralize` for use in a package. When adding `pluralize::pluralize` to a function in my package (whether or not `@import`ing `pluralize`), I would get the following error:

```r
> pl("tree")

Error in .pkgenv$ct$call("pluralize", y, n, prepend) : 
 attempt to apply non-function 
```

This is because the `ct` object in `.pkenv` is only created when `pluralize` is loaded using `library()`.

I believe I have fixed this using `.onLoad()` and will open a PR shortly.

**Comment by KoderKow** [comment]
I have come across this issue as well, are there any plans to merge this fix?
